from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi import Request
from fastapi.responses import JSONResponse
import app.database.db as db
from app.ai import generate_response
from app.database.models import Message, MessageRole

app = FastAPI()


def extract_message_info(body: dict) -> dict:
    entry = body["entry"][0]["changes"][0]["value"]
    return {
        "message": entry["messages"][0],
        "wa_id": entry["contacts"][0]["wa_id"],
        "timestamp": int(entry["messages"][0].get("timestamp")),
        "name": entry["contacts"][0]["profile"]["name"],
    }


def extract_message(message: dict) -> str:
    message_type = message.get("type")
    if message_type == "text":
        return message["text"]["body"]
    elif message_type == "interactive":
        interactive_type = message["interactive"]["type"]
        if interactive_type == "button_reply":
            return message["interactive"]["button_reply"]["title"]
        elif interactive_type == "list_reply":
            return message["interactive"]["list_reply"]["title"]

    return "warning: user sent an unsupported message type"


async def handle_request(request: Request) -> JSONResponse:
    """
    Handles HTTP requests to the 'devhooks' endpoint
    """
    body = await request.json()
    message_info = extract_message_info(body)

    message = extract_message(message_info.get("message", None))

    # wa_id = "+5511999999999"
    # print(f"New message from {message_info['wa_id']}: {message}")

    user = db.get_or_create_user(
        wa_id=message_info["wa_id"], name=message_info.get("name")
    )

    if user.id is None:
        return JSONResponse(
            content={"status": "error", "message": "User ID is missing"},
            status_code=500,
        )

    # Create message record
    user_message = db.create_new_message(
        Message(user_id=user.id, role=MessageRole.user, content=message)
    )

    llm_response = generate_response(user=user, message=user_message)
    if llm_response:
        # Create the response message in the database
        db.create_new_message(llm_response)
    else:
        print("No response generated by LLM")

    return JSONResponse(
        content={"status": "ok"},
        status_code=200,
    )


@app.post("/devhooks")
async def devhooks_post(request: Request) -> JSONResponse:
    return await handle_request(request)
